"""Breed -> size/skull class map for individualized vital baselines.

Breed namespace = the 120 Stanford-Dogs / ImageNet dog synsets (MIT). Each breed
is mapped to a vet-relevant class (toy/large/giant/brachycephalic/sighthound/
chondrodystrophic) used by core.baselines to pick HR/RR/temp ranges.
Generated by tools/build_breed_map.py — see the README Datasets section.
"""

from __future__ import annotations
import re

BREED_CLASS = {
    'affenpinscher': 'brachycephalic',
    'afghan_hound': 'sighthound',
    'airedale_terrier': 'default',
    'alaskan_malamute': 'large',
    'american_staffordshire_terrier': 'default',
    'appenzeller_sennenhund': 'large',
    'australian_kelpie': 'default',
    'australian_silky_terrier': 'toy',
    'australian_terrier': 'default',
    'basenji': 'sighthound',
    'basset_hound': 'chondrodystrophic',
    'beagle': 'default',
    'bedlington_terrier': 'default',
    'bernese_mountain_dog': 'giant',
    'black_and_tan_coonhound': 'default',
    'bloodhound': 'large',
    'bluetick_coonhound': 'default',
    'border_collie': 'large',
    'border_terrier': 'default',
    'borzoi': 'giant',
    'boston_terrier': 'brachycephalic',
    'bouvier_des_flandres': 'large',
    'boxer': 'brachycephalic',
    'briard': 'large',
    'brittany_spaniel': 'default',
    'bullmastiff': 'giant',
    'cairn_terrier': 'chondrodystrophic',
    'cardigan_welsh_corgi': 'chondrodystrophic',
    'chesapeake_bay_retriever': 'large',
    'chihuahua': 'toy',
    'chow_chow': 'default',
    'clumber_spaniel': 'default',
    'cocker_spaniels': 'default',
    'collie': 'large',
    'curly_coated_retriever': 'large',
    'dalmatian': 'default',
    'dandie_dinmont_terrier': 'chondrodystrophic',
    'dobermann': 'large',
    'english_foxhound': 'default',
    'english_setter': 'large',
    'english_springer_spaniel': 'default',
    'entlebucher_sennenhund': 'large',
    'flat_coated_retriever': 'large',
    'french_bulldog': 'brachycephalic',
    'german_shepherd_dog': 'large',
    'german_shorthaired_pointer': 'large',
    'giant_schnauzer': 'default',
    'golden_retriever': 'large',
    'gordon_setter': 'large',
    'great_dane': 'giant',
    'greater_swiss_mountain_dog': 'large',
    'griffon_bruxellois': 'brachycephalic',
    'groenendael': 'default',
    'husky': 'large',
    'ibizan_hound': 'sighthound',
    'irish_setter': 'large',
    'irish_terrier': 'default',
    'irish_water_spaniel': 'default',
    'irish_wolfhound': 'giant',
    'italian_greyhound': 'sighthound',
    'japanese_chin': 'brachycephalic',
    'keeshond': 'default',
    'kerry_blue_terrier': 'default',
    'king_charles_spaniel': 'default',
    'komondor': 'giant',
    'kuvasz': 'giant',
    'labrador_retriever': 'large',
    'lakeland_terrier': 'default',
    'leonberger': 'giant',
    'lhasa_apso': 'brachycephalic',
    'malinois': 'default',
    'maltese': 'toy',
    'mexican_hairless_dog': 'default',
    'miniature_pinscher': 'toy',
    'miniature_poodle': 'default',
    'miniature_schnauzer': 'default',
    'newfoundland': 'giant',
    'norfolk_terrier': 'chondrodystrophic',
    'norwegian_elkhound': 'default',
    'norwich_terrier': 'chondrodystrophic',
    'old_english_sheepdog': 'default',
    'otterhound': 'large',
    'papillon': 'toy',
    'pekingese': 'brachycephalic',
    'pembroke_welsh_corgi': 'chondrodystrophic',
    'pomeranian': 'toy',
    'pug': 'brachycephalic',
    'pyrenean_mountain_dog': 'default',
    'redbone_coonhound': 'default',
    'rhodesian_ridgeback': 'large',
    'rottweiler': 'large',
    'saluki': 'sighthound',
    'samoyed': 'large',
    'schipperke': 'default',
    'scottish_deerhound': 'giant',
    'scottish_terrier': 'chondrodystrophic',
    'sealyham_terrier': 'chondrodystrophic',
    'shetland_sheepdog': 'default',
    'shih_tzu': 'brachycephalic',
    'siberian_husky': 'large',
    'soft_coated_wheaten_terrier': 'default',
    'st_bernard': 'default',
    'staffordshire_bull_terrier': 'default',
    'standard_poodle': 'default',
    'standard_schnauzer': 'default',
    'sussex_spaniel': 'default',
    'tibetan_mastiff': 'giant',
    'tibetan_terrier': 'default',
    'toy_poodle': 'toy',
    'toy_terrier': 'toy',
    'treeing_walker_coonhound': 'default',
    'vizsla': 'large',
    'weimaraner': 'large',
    'welsh_springer_spaniel': 'default',
    'west_highland_white_terrier': 'chondrodystrophic',
    'whippet': 'sighthound',
    'wire_fox_terrier': 'default',
    'yorkshire_terrier': 'toy',
}

# keyword rules (first hit wins) — robust to free-text / mixed breeds
RULES = [
    ('brachycephalic', ['bulldog', 'pug', 'shih', 'pekingese', 'boston', 'boxer', 'brussels', 'griffon', 'lhasa', 'affenpinscher', 'japanese_spaniel', 'chin']),
    ('giant', ['great_dane', 'mastiff', 'saint_bernard', 'newfoundland', 'wolfhound', 'leonberg', 'great_pyrenees', 'kuvasz', 'komondor', 'bernese', 'scottish_deerhound', 'borzoi']),
    ('sighthound', ['greyhound', 'whippet', 'saluki', 'afghan', 'ibizan', 'basenji']),
    ('toy', ['chihuahua', 'pomeranian', 'maltese', 'papillon', 'toy_terrier', 'toy_poodle', 'yorkshire', 'silky', 'japanese', 'italian_greyhound', 'miniature_pinscher']),
    ('chondrodystrophic', ['dachshund', 'corgi', 'basset', 'pembroke', 'cardigan', 'sealyham', 'dandie', 'scottish_terrier', 'west_highland', 'cairn', 'norwich', 'norfolk']),
    ('large', ['retriever', 'shepherd', 'rottweiler', 'doberman', 'husky', 'malamute', 'samoyed', 'collie', 'setter', 'ridgeback', 'weimaraner', 'vizsla', 'pointer', 'bloodhound', 'otterhound', 'akita', 'briard', 'bouvier', 'appenzeller', 'entlebucher', 'greater_swiss']),
]

def _norm(s: str) -> str:
    return re.sub(r'[^a-z0-9]+','_',s.lower()).strip('_')

def classify_breed(name: str) -> str:
    """Resolve a free-text breed name to a vital-baseline class (default if unknown).

    Order: exact Stanford-Dogs breed -> keyword rules (handles mixed/free text).
    """
    if not name:
        return 'default'
    n = _norm(name)
    if n in BREED_CLASS:
        return BREED_CLASS[n]
    for cls, kws in RULES:
        if any(k in n for k in kws):
            return cls
    return 'default'
