#!/usr/bin/env python3
"""Build petvitals/core/breeds.py from the Stanford-Dogs / ImageNet breed taxonomy.

Collects the 120 dog-breed names (public, MIT — ImageNet classes 151-268) and maps
each to a vet-relevant size/skull class used by core.baselines for individualized
HR/RR/temperature ranges. Run to refresh:

    python tools/build_breed_map.py

Source: github.com/anishathalye/imagenet-simple-labels (ImageNet labels) — the same
120 breeds as the Stanford Dogs dataset (vision.stanford.edu/aditya86/ImageNetDogs).
"""

from __future__ import annotations

import json
import re
import urllib.request
from collections import Counter
from pathlib import Path

URL = "https://raw.githubusercontent.com/anishathalye/imagenet-simple-labels/master/imagenet-simple-labels.json"
OUT = Path(__file__).resolve().parent.parent / "petvitals" / "core" / "breeds.py"

# keyword -> vet class (first hit wins). Size/skull drive vital-range adjustment.
RULES = [
    ("brachycephalic", ["bulldog", "pug", "shih", "pekingese", "boston", "boxer",
                         "brussels", "griffon", "lhasa", "affenpinscher",
                         "japanese_spaniel", "chin"]),
    ("giant", ["great_dane", "mastiff", "saint_bernard", "newfoundland", "wolfhound",
               "leonberg", "great_pyrenees", "kuvasz", "komondor", "bernese",
               "scottish_deerhound", "borzoi"]),
    ("sighthound", ["greyhound", "whippet", "saluki", "afghan", "ibizan", "basenji"]),
    ("toy", ["chihuahua", "pomeranian", "maltese", "papillon", "toy_terrier",
             "toy_poodle", "yorkshire", "silky", "japanese", "italian_greyhound",
             "miniature_pinscher"]),
    ("chondrodystrophic", ["dachshund", "corgi", "basset", "pembroke", "cardigan",
                           "sealyham", "dandie", "scottish_terrier", "west_highland",
                           "cairn", "norwich", "norfolk"]),
    ("large", ["retriever", "shepherd", "rottweiler", "doberman", "husky", "malamute",
               "samoyed", "collie", "setter", "ridgeback", "weimaraner", "vizsla",
               "pointer", "bloodhound", "otterhound", "akita", "briard", "bouvier",
               "appenzeller", "entlebucher", "greater_swiss"]),
]


def norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")


def classify(name: str) -> str:
    n = norm(name)
    for cls, kws in RULES:
        if any(k in n for k in kws):
            return cls
    return "default"


def main() -> None:
    labels = json.loads(urllib.request.urlopen(URL, timeout=20).read())
    dogs = labels[151:269]  # the 120 dog breeds
    m = {norm(d): classify(d) for d in dogs}
    print(f"breeds={len(m)} classes={dict(Counter(m.values()))}")

    lines = [
        '"""Breed -> size/skull class map for individualized vital baselines.',
        "",
        "Breed namespace = the 120 Stanford-Dogs / ImageNet dog synsets (MIT). Each breed",
        "is mapped to a vet-relevant class (toy/large/giant/brachycephalic/sighthound/",
        "chondrodystrophic) used by core.baselines to pick HR/RR/temp ranges.",
        "Generated by tools/build_breed_map.py — see the README Datasets section.",
        '"""',
        "",
        "from __future__ import annotations",
        "import re",
        "",
        "BREED_CLASS = {",
    ]
    lines += [f"    {k!r}: {v!r}," for k, v in sorted(m.items())]
    lines += ["}", "", "# keyword rules (first hit wins) — robust to free-text / mixed breeds", "RULES = ["]
    lines += [f"    ({cls!r}, {kws!r})," for cls, kws in RULES]
    lines += [
        "]",
        "",
        "def _norm(s: str) -> str:",
        "    return re.sub(r'[^a-z0-9]+','_',s.lower()).strip('_')",
        "",
        "def classify_breed(name: str) -> str:",
        '    """Resolve a free-text breed name to a vital-baseline class (default if unknown).',
        "",
        "    Order: exact Stanford-Dogs breed -> keyword rules (handles mixed/free text).",
        '    """',
        "    if not name:",
        "        return 'default'",
        "    n = _norm(name)",
        "    if n in BREED_CLASS:",
        "        return BREED_CLASS[n]",
        "    for cls, kws in RULES:",
        "        if any(k in n for k in kws):",
        "            return cls",
        "    return 'default'",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
