#!/usr/bin/env python3
"""Export petvitals EWS results to a TypeScript file the React UI imports.

Runs every analyzer on each available stem, fuses the EWS, and writes
ui/src/generated/petvitalsEws.ts. Re-run whenever analyzers change.

    python tools/export_ews_ui.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

import petvitals  # noqa: E402
from petvitals.core.analyzer import available, get_analyzer  # noqa: E402
from petvitals.core.keypoints import resolve_keypoints_path  # noqa: E402
from petvitals.core.session import Session  # noqa: E402
from petvitals.ews import fuse_ews  # noqa: E402

STEMS = ["1", "3", "4", "5", "6", "7", "8"]
OUT = _ROOT / "ui/src/generated/petvitalsEws.ts"


def _top_posture(summary: dict) -> str:
    frac = summary.get("posture_time_fraction", {})
    return max(frac, key=frac.get) if frac else "n/a"


def build_record(stem: str) -> dict | None:
    if resolve_keypoints_path(stem) is None:
        return None
    session = Session.from_stem(stem)
    results = [get_analyzer(n).analyze(session) for n in available()]
    by_name = {r.name: r for r in results}
    ews = fuse_ews(results)
    pose = by_name.get("pose")
    rppg = by_name.get("rppg")
    hrv = by_name.get("hrv")
    feeding = by_name.get("feeding")
    spo2 = by_name.get("spo2")
    temp = by_name.get("temperature")
    mucous = by_name.get("mucous")
    return {
        "stem": stem,
        "durationSec": session.duration_sec,
        "ews": ews["total_ews"],
        "severity": ews["severity"],
        "baselineSource": rppg.summary.get("baseline_source") if rppg else None,
        "breedClass": rppg.summary.get("breed_class") if rppg else None,
        "byAnalyzer": ews["by_analyzer"],
        "reasons": ews["reasons"],
        "vitals": {
            "hrBpm": rppg.summary.get("hr_bpm") if rppg else None,
            "rrBpm": rppg.summary.get("rr_bpm") if rppg else None,
            "pantingIntensity": rppg.summary.get("panting_intensity") if rppg else None,
            "sdnnMs": hrv.summary.get("sdnn_ms") if hrv else None,
            "hrvAvailable": bool(hrv.summary.get("hrv_available")) if hrv else False,
            "spo2Pct": spo2.summary.get("spo2_pct") if spo2 else None,
            "tempC": temp.summary.get("temp_c") if temp else None,
            "mmColor": (mucous.summary.get("mm_color")
                        if mucous and mucous.summary.get("usable_read") else None),
        },
        "behavior": {
            "topPosture": _top_posture(pose.summary) if pose else "n/a",
            "meanActivity": pose.summary.get("mean_activity") if pose else None,
            "oralEvents": feeding.summary.get("oral_events") if feeding else None,
        },
        "flags": sorted({
            k for r in results for k, v in r.summary.get("flags", {}).items() if v
        }),
    }


def main() -> None:
    records = [r for r in (build_record(s) for s in STEMS) if r]
    payload = {
        "note": "Auto-generated by tools/export_ews_ui.py — do not edit by hand.",
        "analyzers": available(),
        "patients": records,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    types = (
        "export interface EwsPatient {\n"
        "  stem: string;\n  durationSec: number;\n  ews: number;\n  severity: string;\n"
        "  baselineSource: string | null;\n  breedClass: string | null;\n"
        "  byAnalyzer: Record<string, number>;\n  reasons: string[];\n"
        "  vitals: { hrBpm: number | null; rrBpm: number | null; pantingIntensity: number | null;"
        " sdnnMs: number | null; hrvAvailable: boolean; spo2Pct: number | null; tempC: number | null;"
        " mmColor: string | null };\n"
        "  behavior: { topPosture: string; meanActivity: number | null; oralEvents: number | null };\n"
        "  flags: string[];\n}\n\n"
        "export interface PetVitalsEws {\n  note: string;\n  analyzers: string[];\n"
        "  patients: EwsPatient[];\n}\n\n"
    )
    ts = ("// AUTO-GENERATED by tools/export_ews_ui.py — do not edit.\n\n"
          + types
          + "export const PETVITALS_EWS: PetVitalsEws = "
          + json.dumps(payload, indent=2, ensure_ascii=False) + ";\n")
    OUT.write_text(ts, encoding="utf-8")
    print(f"[export] wrote {OUT.relative_to(_ROOT)} with {len(records)} patients")
    for r in records:
        print(f"  stem {r['stem']}: EWS {r['ews']} ({r['severity']})  "
              f"HR={r['vitals']['hrBpm']} RR={r['vitals']['rrBpm']}  flags={r['flags']}")


if __name__ == "__main__":
    main()
